name: CI

on:
  [ push, pull_request ]

jobs:
  test-options:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run script test_options
        run: python3 test/test_options.py