name: Bug report
description: Fill a bug report
labels: [ "bug" ]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the problem
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: Tell us how we can reproduce the bug, it's the best way to help us to fix it.
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible solution
      description: "Optional: if you have an idea how to fix it, don't hesitate to also open a pull request"
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: "Optional: Add any other context about the problem here. Like your OS, C++ compiler, ..."