name: Changes check

on:
  push:
    paths:
      - "src/lib/grammar/FilLexer.g4"
      - "src/lib/grammar/FilParser.g4"
      - ".github/workflows/changes.yml"

jobs:
  diagram:
    name: Diagram check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate diagram
        run: ${{github.workspace}}/bin/railroad_diagram.sh
      - name: Check no changes
        run: ${{github.workspace}}/bin/check_no_changes.sh