name: Coverage

on:
  push:
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/coverage.yml"
  pull_request:
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/coverage.yml"
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: 10
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Coverage
      - name: Build
        run: cmake --build ${{github.workspace}}/build --target coverage

      - name: Codacy coverage report
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{github.workspace}}/build/coverage.info
