name: Tests

on:
  push:
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/coverage.yml"
  pull_request:
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/coverage.yml"
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-20.04, macos-12, macos-11 ]
        ## windows-2022, windows-2019 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: 10

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Coverage
      - name: Build
        run: cmake --build ${{github.workspace}}/build --target coverage

      - name: Codacy coverage report
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{github.workspace}}/build/coverage.info
