name: filc

on:
  [ push, pull_request ]

jobs:
  nothing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "nothing"
#  test-options:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: run script test_options
#        run: python3 filc/test/test_options
#      - run: ls
