name: Packaging

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev-build
    tags:
      - '*'

jobs:
  build:
    name: "[${{ matrix.job.os }}] - ${{ matrix.job.target }}"
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: x86_64-unknown-linux-gnu , os: ubuntu-20.04, pkg-name: amd64 }
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15"
          env: true

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release --toolchain=cmake/toolchains/${{ matrix.job.target }}.toolchain.cmake

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --target filc

      - name: Get metadata
        id: metadata
        run: |
          BINARY_PATH=${{ github.workspace }}/build/filc
          echo "BINARY_PATH=${BINARY_PATH}" >> $GITHUB_OUTPUT
          
          PACKAGE_VERSION=$(cat VERSION)
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_OUTPUT

      - name: Create Debian package
        if: startsWith(matrix.job.os, 'ubuntu')
        id: debian_package
        run: |
          DEB_PKG_NAME=filc_${{ steps.metadata.outputs.PACKAGE_VERSION }}_${{ matrix.job.pkg_name }}.deb
          ${{ github.workspace }}/bin/build_deb_package.sh ${{ steps.metadata.outputs.BINARY_PATH }} ${{ steps.metadata.outputs.PACKAGE_VERSION }} ${{ matrix.job.pkg_name }}
          mv filc.deb $DEB_PKG_NAME
          echo "DEB_PKG_NAME=${DEB_PKG_NAME}" >> $GITHUB_OUTPUT

      - name: "Artifact upload: Debian package"
        if: steps.debian_package.outputs.DEB_PKG_NAME
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.debian_package.outputs.DEB_PKG_NAME }}
          path: ${{ github.workspace }}/${{ steps.debian_package.outputs.DEB_PKG_NAME }}
