name: Package

on:
  push:
    branches:
      - master
      - dev-workflow
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

      - name: Install Nix
        uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
      - name: Build
        run: nix-shell --pure --run 'bazel build //:filc'

      - name: Archive binary
        uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4.3.5
        with:
          name: filc
          path: ${{ github.workspace }}/bazel-bin/filc
