name: Tests

on:
  push:
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/test.yml"

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install LLVM
        if: matrix.os == 'macos-latest'
        run: brew install llvm
      - name: Install LLVM
        if: matrix.os == 'windows-latest'
        run: choco install llvm --version 10.0.0

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Prepare test
        run: |
          cd ${{github.workspace}}/test
          npm install
      - name: Run test
        run: |
          cd ${{github.workspace}}/test
          npm test
      - name: Archive tests logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: tests-logs ${{ matrix.os }}
          path: ${{github.workspace}}/test/log.txt
          retention-days: 1