name: Tests

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/test.yml"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-20.04, macos-12, macos-11 ]
        ## windows-2022, windows-2019 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: 10
      - name: Setup LCOV
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Configure CMake
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON
      - name: Configure CMake
        if: ${{ matrix.os != 'ubuntu-22.04' }}
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build ${{github.workspace}}/build --target tests

      - name: Run tests
        run: cd ${{github.workspace}}/build && ctest

      # Run coverage reports only for ubuntu-22.04
      - name: Generate coverage report
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: ${{github.workspace}}/coverage.sh
      - name: Upload coverage reports to Codacy
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{github.workspace}}/coverage.info
          language: cpp
      - name: Upload coverage reports to Codecov
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{github.workspace}}/coverage.info
