name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: "Build & Run"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@3715ab1a11cac9e991980d7b4a28d80c7ebdd8f9 # v28
      - name: Build then run
        run: |
          nix-shell --run 'build_release'
          
          ${{ github.workspace }}/filc

  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@3715ab1a11cac9e991980d7b4a28d80c7ebdd8f9 # v28
      - name: Run tests
        run: nix-shell --run 'run_unit_tests'

      - name: Build coverage
        run: nix-shell --run 'build_coverage'
      - name: Upload coverage report to Codacy
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{ github.workspace }}/coverage.info

  e2e-tests:
    name: "e2e tests"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@3715ab1a11cac9e991980d7b4a28d80c7ebdd8f9 # v28
      - name: Run tests
        run: nix-shell --run 'run_e2e_tests'

  clang-format:
    name: "Run clang-format"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@3715ab1a11cac9e991980d7b4a28d80c7ebdd8f9 # v28
      - name: Run clang-format
        run: nix-shell --run 'run_clang-format'
      - name: Check no changes
        run: nix-shell --run 'check_no_changes'
