name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: "Build & Run"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

      - name: Install Nix
        uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
      - name: Build then run
        run: nix-shell --pure --run 'bazel run //:filc'

  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

      - name: Install Nix
        uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
      - name: Run tests
        run: nix-shell --pure --run 'bazel test //:unit-tests'
