name: Tests

on:
  push:
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/test.yml"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-20.04, macos-12, macos-11 ]
        ## windows-2022, windows-2019 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: 10

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build ${{github.workspace}}/build --target tests

      - name: Run tests
        run: cd ${{github.workspace}}/build && ctest
