name: Tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  CC: clang # Force usage of clang

jobs:
  configure:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - name: Set matrix data
        id: set-matrix
        run: |
          echo 'matrix<<EOF' >> "$GITHUB_OUTPUT"
          echo "$(cat ./tools/ci/build-matrix.json)" >> "$GITHUB_OUTPUT"
          echo EOF >> "$GITHUB_OUTPUT"

  build:
    name: "Build & Run [${{ matrix.os }} - ${{ matrix.platform }}]"
    needs: configure
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

      - name: Install Nix
        uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
      - name: Build then run
        run: nix-shell --pure --run '${{ github.workspace }}/tools/ci/build_and_run.sh ${{ matrix.platform }}'

  unit-tests:
    name: "Unit tests [${{ matrix.os }} - ${{ matrix.platform }}]"
    needs: configure
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

      - name: Install Nix
        uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
      - name: Run tests
        run: nix-shell --pure --run '${{ github.workspace }}/tools/ci/run_unit_tests.sh ${{ matrix.plaform }}'

  test-coverage:
    name: "Unit test coverage"
    needs: configure
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

      - name: Install Nix
        uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
      - name: Run tests
        run: nix-shell --pure --run 'bazel coverage --combined_report=lcov //:unit-tests'
      - name: Get report path
        id: path
        run: |
          nix-shell --pure --run 'echo "$(bazel info output_path)/_coverage/_coverage_report.dat" > path.txt'
          echo "path=$(cat path.txt)" >> "$GITHUB_OUTPUT"
      - name: Upload coverage report to Codacy
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{ steps.path.outputs.path }}
